name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run go vet
        run: "go vet ./..."
      - name: Run golangci-lint
        uses: dominikh/staticcheck-action@v1.0.0
        with:
          version: latest
